### ISSUE TITLE
freqz() is evaluating filter coefficients backwards

### ISSUE THREAD

**Issue by btiburcio** [JuliaDSP/DSP.jl#135]
Feeding freqz() with PolynomialRatio(b,a) where b and a are vectors containing the filter coefficients in decreasing powers of e^(jω) will cause freqz() to evaluate the frequency response of the polynomial ratio of b and a in increasing powers of e^(jω). Which in most cases, will only give a wrong phase response. Issue #118 is most likely related to this one.

**Comment by ma-laforge** [comment]
Actually, it is `PolynomialRatio()` that interprets the coefficients in the reverse order that you would expect:

```
using DSP
b=[10,20,30,40]
a=[1,2,3,4]
p = PolynomialRatio(b, a)

@show p #=> p = DSP.Filters.PolynomialRatio{Int64}(Poly(40 + 30⋅x + 20⋅x^2 + 10⋅x^3),Poly(4 + 3⋅x + 2⋅x^2 + x^3))
@show p.b #=> p.b = Poly(40 + 30⋅x + 20⋅x^2 + 10⋅x^3)
```

I must agree: it is a bit odd that `PolynomialRatio()` reverses the order of the input coefficients before constructing `Polynomials.Poly()`.

It would be much more intuitive if:
```
PolynomialRatio([b0, b1, ..., bn], [a0, a1, ..., an])
```

created polynomial:
```
 (b0⋅x^0+b1⋅x^1+...+bn⋅x^n) / (a0⋅x^0+a1⋅x^1+...+an⋅x^n)
```

instead of:
```
 (bn⋅x^0+...+b1⋅x^(n-1)+b0⋅x^n) /  (an⋅x^0+...+a1⋅x^(n-1)+a0⋅x^n)
```

**Comment by ma-laforge** [comment]
As a side note:

I find it relatively confusing that `PolynomialRatio` stores the numerator & denominator as `.b` & `.a` respectively (I think).

It would be much clearer if `PolynomialRatio` used field names: `.num` & `.denom`.

It would also be nice if the `show()` method of `PolynomialRatio` could somehow hint as to which `Poly` is the numerator and which is the denominator, instead of the current display:
```
DSP.Filters.PolynomialRatio{Int64}(Poly(40 + 30⋅x + 20⋅x^2 + 10⋅x^3),Poly(4 + 3⋅x + 2⋅x^2 + x^3))
```

**Comment by martinholters** [comment]
With #284 we now have:
```julia
julia> b=[10,20,30,40];

julia> a=[1,2,3,4];

julia> p = PolynomialRatio(b, a)
PolynomialRatio{:z, Float64}(Polynomials.LaurentPolynomial(40.0*z⁻³ + 30.0*z⁻² + 20.0*z⁻¹ + 10.0), Polynomials.LaurentPolynomial(4.0*z⁻³ + 3.0*z⁻² + 2.0*z⁻¹ + 1.0))

julia> p = PolynomialRatio{:s}(b, a)
PolynomialRatio{:s, Int64}(Polynomials.LaurentPolynomial(40 + 30*s + 20*s² + 10*s³), Polynomials.LaurentPolynomial(4 + 3*s + 2*s² + s³))
```
So the arguments to `PolynomialRatio{:z}` are ordered in increasing power of `z⁻¹`, for `PolynomialRatio{:s}` they are ordered in decreasing power of `s`. While that is reversed compared to how `Polynomials` does it and the printing is unfortunate, this order seems to be more common in signal processing and is also clearly documented now. So closing, but please comment if you disagree.
