### ISSUE TITLE
Adding Unwrap.jl to JuliaDSP

### ISSUE THREAD

**Issue by platawiec** [JuliaDSP/DSP.jl#196]
I've written arbitrary-dimensional phase unwrapping in the [Unwrap.jl](https://github.com/platawiec/Unwrap.jl) package. See the README for more info.

@bjarthur had asked me to combine the code into the DSP org, either as part of DSP.jl or a separate package in the org. The code is at the point where I'm comfortable doing either - I'd like to get the community's perspective on the best way forward. Once it's settled I can make a PR.

**Comment by ssfrr** [comment]
Looks cool. I'd support merging this into DSP.jl rather than a separate package.

The current `unwrap` function in DSP.jl allows you to specify the wrap overflow amount. I generally use it for phase unwrapping at 2pi so I don't need it to be configurable, but I assume some folks must want that. How hard would it be to make it configurable in your implementations?

**Comment by platawiec** [comment]
Thanks for the feedback - that shouldn't be hard to implement. I'll submit a PR to DSP.jl when I'm done.
