### ISSUE TITLE
remez for FIR filters

### ISSUE THREAD

**Issue by sirtom67** [JuliaDSP/DSP.jl#199]
I have ported scipy's remez and started a wrapper for it.
I think this would be the first "C" source code in DSP and I have a couple questions.
1) where should the source files go (currently it is a single .h, .c, and a Makefile).
2) how would this get built? So far I just manually run "make" with my Makefile and set the LD_LIBRARY_PATH prior to starting julia to include the location of the ".so" file.
3) any license issues? Would need to include scipy's license terms somehow.
I'm still new to julia, thanks for your help!
- Tom

**Comment by ssfrr** [comment]
To answer your question about build process, the latest and greatest is to use [BinaryBuilder.jl](https://github.com/JuliaPackaging/BinaryBuilder.jl) to build cross-platform binaries and [BinaryProvider.jl](https://github.com/JuliaPackaging/BinaryProvider.jl) to download and install the built binaries to the user's machine during the package's build.

I'm not sure what other folks think, but I'm a little concerned about including a binary dependency in DSP.jl, which is depended on by a lot of other packages, and sometimes just so that they can extend methods in it. If DSP.jl gets too heavy than we're going to want to split out the interface functions into a DSPBase.jl to be used by other packages that want to extend DSP functionality.

It's possible that with the upcoming Pkg3 speed improvements, slicker binary install with BinaryProvider, and post-1.0 precompile speed improvements these concerns will be moot, but I don't have enough experience with any of those to make a judgement call.

Can you clarify what  scipy's remez functionality does over and above the existing filter design features?

**Comment by martinholters** [comment]
The obvious way forward would be to port the algorithm to Julia. But I have to admit I have no idea how much work that would be. Can you post a link to (or create a gist with) the c code so that I can get a feel?

**Comment by martinholters** [comment]
> I am interested in attempting a rewrite.

That would be great! The remez algorithm would surely be a very valuable tool to have. Looking at the C code, I'm also a bit doubtful porting that (again) is the right approach here. Whatever you come up with, I'm looking forward to it!

**Comment by sirtom67** [comment]
Quick update: I am making slow progress on the re-implementation in Julia.

**Comment by sirtom67** [comment]
Just added PR #210 to address this issue. It is a Julia translation of Travis Oliphant's port of Egal Kvaleberg's C translation of James McClellan's FORTRAN.

The current function returns just a vector - not a filter type. I prefer to keep FIR filters simple like that but am willing to entertain the "right" return type that is consistent with the other FIR design functions.

Note I also created a new repo with a wrapper for the SCIPY C function: [DSPRemezWrap.jl](https://github.com/sirtom67/DSPRemezWrap.jl).

**Comment by sirtom67** [comment]
Hey! We did it! DSP has remez now. Closing the issue :-)
