### ISSUE TITLE
Rename conv2 to conv

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDSP/DSP.jl#202]
Just like we did for `fft2`, should we not replace `conv2` with `conv` and just use dispatch?

**Comment by martinholters** [comment]
Sounds like a good idea to me.

**Comment by monsij** [comment]
Can I be briefed about the task and get assigned too? @ViralBShah

**Comment by martinholters** [comment]
I think we can just rename the two `conv2(::StridedMatrix, ::StridedMatrix)` methods to `conv`. In the light of #224, `conv2(::StridedVector, ::StridedVector, ::StridedMatrix)` should probably become `conv2(::StridedVector, ::Transposed{_,<:StridedVector}, ::StridedMatrix)` (and/or `Adjoint` instead of `Transposed`?). That would leave the door open for future implementation of full multi-arg `conv` as proposed in #224.

Of course, deprecations should be put into place so that `conv2(...)` still works, but prints a warning to rather use `conv(...)`.

**Comment by HDictus** [comment]
I'd like to express support for this idea - along with future extension to convolution in any number of dimensions. 
I do think it would best to have a keyword argument to specify the dimensions to convolve along (like cat does) - both to disambiguate implementations and allow further extensions for e.g. 2 dimensional convolution over data of shape (Height, Width, in_channels, N_images) with a filter of shape (h, w, in_channels, out_channels), along the first two dimensions, as is required for certain machine learning applications.

**Comment by HDictus** [comment]
Is someone already working on this? I'm realizing that  #264  would be a lot quicker to do after this issue, rather than before, and could cause some tricky merge conflicts if someone is already halfway through this.

If no one is, mind if I take a swing?

**Comment by HDictus** [comment]
I'll work on this for now

**Comment by galenlynch** [comment]
Implemented in #269
