### ISSUE TITLE
Filter Coefficient Priniting 

### ISSUE THREAD

**Issue by hamzaelsaawy** [JuliaDSP/DSP.jl#255]
I have functionality to pretty-print transfer functions:

![image](https://user-images.githubusercontent.com/22927537/52169451-adc27480-2706-11e9-9d15-6f9c0b02bd13.png)

But currently I am using a global setting struct to pick between printing H(z) or H(s).
It works well, but problem is, its a global variable...

Is there any interest in creating a wrapper struct to specify discrete or continuous?

```julia
abstract type Filter{T<:Number, FC<:FilterCoefficients} end
struct DiscreteFiler{T<:Number, FC<:FilterCoefficients} 
    fc::FC{T}
    ωc::Real
end
struct AnalogFilter{T<:Number, FC<:FilterCoefficients} 
    fc::FC{T}
end
```

That would simplify the `freqz/freqs` interface, and be more inline with the `analog/digitalfilter` methods

**Comment by ma-laforge** [comment]
I personally like the idea of having types to discriminate between discrete vs continuous-time filters as well.

### Multiple-dispatch & safety
I really like the idea of being able to dispatch on a either a continous-time filtering algorithm vs a discrete-time filtering algorithm, depending on the filter type.  I also like the added checks this would give you if you tried to call a continuous-time operation with a discrete-time filter (and vice-versa).

### Sampling frequencies
However, I am not convinced there is a need for the sampling frequency on the filter definition.  Sampling frequency is typically a system-wide property.  It is not filter dependent.  I would therefore remove the `ωc` component from the discrete filter implementation.

### New possibility: native filter definitions
If we remove the `ωc` component from the discrete filter implementation, it would permit us to simplify the parameterization of the "filter object".  That would make it easier to do things like having a way to natively define filters as a ratio of polynomials ***as well as a collection of poles & zeros***.

Algorithms could therefore use simple transformation operations to convert between polynomial <--> pole-zero filter definitions.  This is very useful because certain algorithms are better suited to for one form or another.

Maybe the filter object could look something like the following:

```
abstract type Filter{CT<:Bool}

struct FilterPoly{CT<:Bool} <: Filter{CT<:Bool}
	#Polynomial implementation
end
struct FilterPZ{CT<:Bool} <: Filter{CT<:Bool}
	#Pole-zero implementation
end


#Aliases to be used by function signatures to specialize on
#discrete vs continuous time:
FilterCT = Filter{true}
FilterDT = Filter{false}
```

###  Development

I very much appreciate that you have noticed this potential improvement to the DSP.jl API.  I myself have occasionnally encountered issues that brought me to similar conclusions.

Having said that, I don't think you will easily convince someone else to develop this for you.  Not everyone understands the potential improvements this might bring to the usability of the module.

I think you might be the best one to experiment along this path:
  1. You recognize the need for an improvement.
  2. You likely have an application in mind that would help you flesh out this idea.

Both these properties are essential to making an actual improvement to the module. In the past, I have found that a good idea is not acually a good idea until you have an application to make it concrete.  We often over-simplify things in our imagination that need to be delt with when it is time to deal with real-world problems.

So I hope you will give it a shot.  I am all for an improvement in the API.

Note that I am willing to answer questions if you have them... but you should be aware that I am not a maintainer of the DSP.jl module: Just because I think something is a good idea doesn't mean that the maintainers will want to integrate the changes you propose - sorry.
