### ISSUE TITLE
Broken documentation link in periodograms.jl

### ISSUE THREAD

**Issue by NikStoyanov** [JuliaDSP/DSP.jl#289]
Reading through the code in *periodograms.jl* I noticed that the explanation file referenced in the header cannot be loaded. The relevant code line is here: https://github.com/JuliaDSP/DSP.jl/blob/3b7716fcce890650a18f38d4195e633613908815/src/periodograms.jl#L4 and the file is supposed to be at: http://www.ee.lamar.edu/gleb/adsp/Lecture%2008%20-%20Nonparametric%20SE.pdf

Would you happen to know where the file was relocated and I can send a PR.

**Comment by galenlynch** [comment]
Looks like it was added by @kofron in the first commit.

**Comment by kofron** [comment]
The original lectures are by Dr. Gleb Tcheslavski, but it looks like they've been moved and I can't find them.  

Because the linked documents really just describe the methods and not the specific implementations I'd lobby to just remove the link - it would probably be possible to find a replacement but risks playing pdf whack-a-mole if that document gets subsequently (re)moved.

**Comment by NikStoyanov** [comment]
That makes sense. I have updated the module docstring.
