### ISSUE TITLE
conv between fixed-point array and integer array results in OOM

### ISSUE THREAD

**Issue by fghzxm** [JuliaDSP/DSP.jl#352]
`conv` between an `Array{FixedPointNumbers.Fixed{T,f}}` and an `Array{Int}` results in OOM.

Reproduction:
```julia
using FixedPointNumbers, DSP;
conv(Array{Q0f15}(undef, 100000), [-1, 1])
```

**Comment by galenlynch** [comment]
Thanks for posting this bug, I'll look into it tonight.

**Comment by galenlynch** [comment]
It seems like one of the `conv` conversion methods has overly strict type bounds. I'll fix it in a PR.

Right now, it looks like `conv` will automatically convert fixed point numbers into BLAS floating point numbers, which is behavior inherited from Julia base. I'm not sure if there's still a good reason to do this, since I think this conversion was for the sake of the `FFTW` calls inside of `conv`. I need to do some testing, but I think that all the code in `conv` should be fine without this conversion. If tha'ts the case, then perhaps it would make sense to remove this conversion to keep the element type of the inputs, though it would technically be a breaking change.

**Comment by galenlynch** [comment]
This example triggers the same error, without using `FixedPointNumbers`:

```julia
using DSP;
conv([1//2, 1//3, 1//4], [1, 2])
```

**Comment by rob-luke** [comment]
I have a question about the fixed point numbers, not the `x//y` operator you provide above. I comment here because the fix in #353 looks great for `//`.

If you make the breaking changes to keep the element type, will the entire conv operation be performed using fixed point numbers/operations? Or will it convert to something float like somewhere along the line for computation? I am trying to put myself in the mind of a `FixedPointNumbers` user. I assume these users are trying to understand the effect that operating in fixed point will have on their processing, perhaps in preparation for converting their code to a fixed point DSP hardware. In this case, the user would want all operations to be performed in fixed point, not converted to float and then converted back to fixed along the way.

Personally I would love to have full support for fixed point operations. I have not looked in to it (so would be pleased to be corrected here), but it may be that enforcing all downstream operations to operate in fixed point is currently beyond the scope of `DSP.jl`, and in that case should we throw an error or warning if a user passes in fixed point numbers. Something like `@warn(Input contains fixed point numbers. Some processing steps may be computed after conversion to float.)`. What are your thoughts @galenlynch?

**Comment by galenlynch** [comment]
From what I can tell, things are converted into floating point numbers before any FFT/IFFT happens, and the result is returned as a float. Now that I think about it, I think the current behavior of just returning a float might be the most honest, and has the least potential to cause problems by attempting to assign floating point numbers to arrays with a different element type. I think letting the user convert it back into the type that they want also seems reasonable. If people are using this library to see what would happen if convolution was implemented with fixed point numbers, then our `conv` won't do that regardless. At the moment it uses overlap-save fast convolution with FFTW to do FFT/IFFT, which just converts fixed point numbers into floats.

**Comment by galenlynch** [comment]
Whoops, this was closed because I merged #353, but the issue about what data type to return for input arrays of fixed point numbers remains unsolved. Perhaps we should split that off into a separate issue?

**Comment by fghzxm** [comment]
> Perhaps we should split that off into a separate issue?

No problem.  Thanks for resolving this issue.

**Comment by rob-luke** [comment]
I agree that returning a float is the most honest and clear approach. That way there should be no confusion that internal computations are performed using floating point numbers.
