### ISSUE TITLE
Filter order

### ISSUE THREAD

**Issue by vitorn** [JuliaDSP/DSP.jl#429]
Is there a function to compute the required order for a Butterworth, Chebyshev or Kauer filter?  How about for min-max (Remez, Parks-McClellan) FIR filters?  I only found kaiserord, for Kaiser window FIR filters.

**Comment by jsmithnh09** [comment]
The Butterworth filter approximation is something I'll give a shot at! I _think_ I have some suitable code for the lowpass and highpass cases, but I'll need to work out the bandpass and bandstop cases since those are a little trickier. I'm putting together test cases for these as well, based on [the examples on Mathworks' site.](https://www.mathworks.com/help/signal/ref/buttord.html)

**Comment by jsmithnh09** [comment]
I believe the PR in #453 addresses the majority of the filter design cases here, I think the only outstanding one is parameter estimation for Parks-McClellan FIR filters.

**Comment by jsmithnh09** [comment]
@vitorn We've added the filter order estimation schemes you requested, hopefully this closes out your issue!

**Comment by martinholters** [comment]
Indeed, this seems fixed now. Comment if you disagree.
