### ISSUE TITLE
new version?

### ISSUE THREAD

**Issue by samtkaplan** [JuliaDSP/DSP.jl#462]
Hi,

I am having an issue where DSP's dependence on Polynomials < 3.0 is causing a bug where the TimeZones `format` method get dispatched to instead of the version of `format` in the `Dates` stdlib.  It looks like registering a new version of this package will solve the problem for me.  Would you be willing to burn another version number?

Thanks!

Sam

![image](https://user-images.githubusercontent.com/4575854/155408562-a9fe3129-1b2a-41b2-a534-d771a6a8e24f.png)

**Comment by martinholters** [comment]
Sure, we can tag another release, no problem.

To have it on record somewhere: The issue is that Polynomials prior to 3.0.0 depends on Intervals.jl which in turn depends on TimeZones.jl which suffers from https://github.com/JuliaTime/TimeZones.jl/issues/374. Ideally, that gets fixed and a new version of TimeZones.jl gets tagged. But just tagging a new version here is likely quicker and allows to circumvent the problem, and I don't see why we shouldn't do it.
